"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { createClient } from "@/lib/supabase/client"

type Form = { first_name:string; last_name:string; phone:string; city:string; postal_code:string; profession:string; headline:string; bio:string; education:string; years_experience:string; desired_salary_min:string; desired_salary_max:string; desired_employment_percent:string; preferred_radius_km:string; available_from:string; remote_ok:boolean; shift_work_ok:boolean; driving_license_b:boolean; skills:string; languages:string; profile_visible:boolean; contact_visible:boolean }
const initial:Form = {first_name:"",last_name:"",phone:"",city:"",postal_code:"",profession:"",headline:"",bio:"",education:"",years_experience:"",desired_salary_min:"",desired_salary_max:"",desired_employment_percent:"100",preferred_radius_km:"30",available_from:"",remote_ok:false,shift_work_ok:false,driving_license_b:false,skills:"",languages:"",profile_visible:true,contact_visible:false}

export default function EmployeeProfilePage(){
  const [form,setForm]=useState(initial); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState(""); const [avatar,setAvatar]=useState<File|null>(null)
  useEffect(()=>{(async()=>{const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.href="/login";return}; const [{data:p},{data:e}]=await Promise.all([supabase.from("profiles").select("first_name,last_name,phone,city,postal_code").eq("id",user.id).maybeSingle(),supabase.from("employee_profiles").select("profession,headline,bio,education,years_experience,desired_salary_min,desired_salary_max,desired_employment_percent,preferred_radius_km,available_from,remote_ok,shift_work_ok,driving_license_b,skills,languages,profile_visible,contact_visible").eq("id",user.id).maybeSingle()]); setForm({...initial,...p,...e,years_experience:e?.years_experience?.toString()??"",desired_salary_min:e?.desired_salary_min?.toString()??"",desired_salary_max:e?.desired_salary_max?.toString()??"",desired_employment_percent:e?.desired_employment_percent?.toString()??"100",preferred_radius_km:e?.preferred_radius_km?.toString()??"30",skills:e?.skills?.join(", ")??"",languages:e?.languages?.join(", ")??"",available_from:e?.available_from??""}); setLoading(false)})()},[])
  const set=(k:keyof Form,v:string|boolean)=>setForm(x=>({...x,[k]:v}))
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setNotice("");const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login";return}
    let avatar_url: string|undefined
    if(avatar){const ext=avatar.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${user.id}/avatar.${ext}`;const up=await supabase.storage.from("employee-media").upload(path,avatar,{upsert:true,contentType:avatar.type});if(up.error){setNotice(up.error.message);setSaving(false);return}const {data}=supabase.storage.from("employee-media").getPublicUrl(path);avatar_url=data.publicUrl}
    const profile={id:user.id,first_name:form.first_name||null,last_name:form.last_name||null,email:user.email??null,phone:form.phone||null,city:form.city||null,postal_code:form.postal_code||null,...(avatar_url?{avatar_url}:{})}; const employee={id:user.id,profession:form.profession||null,headline:form.headline||null,bio:form.bio||null,education:form.education||null,years_experience:form.years_experience?Number(form.years_experience):0,desired_salary_min:form.desired_salary_min?Number(form.desired_salary_min):null,desired_salary_max:form.desired_salary_max?Number(form.desired_salary_max):null,desired_employment_percent:Number(form.desired_employment_percent)||100,preferred_radius_km:Number(form.preferred_radius_km)||30,available_from:form.available_from||null,remote_ok:form.remote_ok,shift_work_ok:form.shift_work_ok,driving_license_b:form.driving_license_b,skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean),languages:form.languages.split(",").map(x=>x.trim()).filter(Boolean),profile_visible:form.profile_visible,contact_visible:form.contact_visible};
    const a=await supabase.from("profiles").upsert(profile); const b=await supabase.from("employee_profiles").upsert(employee); if(a.error||b.error)setNotice(a.error?.message||b.error?.message||"Speichern fehlgeschlagen"); else setNotice("Profil erfolgreich gespeichert."); setSaving(false)
  }
  if(loading)return <main className="flex min-h-screen items-center justify-center bg-[#f7f8fa] text-slate-500">Profil wird geladen…</main>
  return <main className="min-h-screen bg-[#f7f8fa]"><header className="border-b bg-white"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6"><Link href="/arbeitnehmer" className="text-2xl font-black">Stoyan<span className="text-blue-600">.</span></Link><Link href="/arbeitnehmer" className="text-sm font-bold text-slate-600">← Zurück zum Dashboard</Link></div></header><div className="mx-auto max-w-5xl px-6 py-10"><div><p className="text-sm font-bold uppercase tracking-widest text-blue-600">Mein Profil</p><h1 className="mt-2 text-4xl font-black">Präsentiere dich professionell.</h1><p className="mt-3 text-slate-600">Je vollständiger dein Profil ist, desto besser können passende Arbeitgeber dich einschätzen.</p></div><form onSubmit={save} className="mt-8 space-y-6">
    <section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Persönliche Daten</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["first_name","Vorname"],["last_name","Nachname"],["phone","Telefon"],["city","Ort"],["postal_code","PLZ"]].map(([k,l])=><label key={k} className="text-sm font-bold"><span>{l}</span><input value={form[k as keyof Form] as string} onChange={e=>set(k as keyof Form,e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-blue-600"/></label>)}<label className="text-sm font-bold"><span>Profilbild</span><input type="file" accept="image/*" onChange={e=>setAvatar(e.target.files?.[0]??null)} className="mt-2 block w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"/></label></div></section>
    <section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Berufliche Präsentation</h2><div className="mt-6 space-y-4"><label className="text-sm font-bold">Beruf<input value={form.profession} onChange={e=>set("profession",e.target.value)} placeholder="z. B. Automobil-Mechatroniker EFZ" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Profil-Überschrift<input value={form.headline} onChange={e=>set("headline",e.target.value)} placeholder="z. B. Erfahrener Mechatroniker mit Schwerpunkt Diagnose" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Über mich<textarea value={form.bio} onChange={e=>set("bio",e.target.value)} rows={5} placeholder="Beschreibe dich, deine Stärken und deine beruflichen Ziele…" className="mt-2 w-full resize-y rounded-xl border px-4 py-3 font-normal"/></label></div></section>
    <section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Ausbildung & Erfahrung</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Ausbildung<input value={form.education} onChange={e=>set("education",e.target.value)} placeholder="z. B. EFZ Automobil-Mechatroniker" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Berufserfahrung (Jahre)<input type="number" min="0" step="0.5" value={form.years_experience} onChange={e=>set("years_experience",e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Verfügbar ab<input type="date" value={form.available_from} onChange={e=>set("available_from",e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label></div></section>
    <section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Skills & Sprachen</h2><div className="mt-6 grid gap-4"><label className="text-sm font-bold">Skills <span className="font-normal text-slate-400">(mit Komma trennen)</span><input value={form.skills} onChange={e=>set("skills",e.target.value)} placeholder="Diagnose, BMW, MFK, Reparatur" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Sprachen <span className="font-normal text-slate-400">(mit Komma trennen)</span><input value={form.languages} onChange={e=>set("languages",e.target.value)} placeholder="Deutsch B2, Englisch B1" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label></div></section>
    <section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Deine Arbeitswünsche</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Wunschlohn ab<input type="number" value={form.desired_salary_min} onChange={e=>set("desired_salary_min",e.target.value)} placeholder="CHF" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Wunschlohn bis<input type="number" value={form.desired_salary_max} onChange={e=>set("desired_salary_max",e.target.value)} placeholder="CHF" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Gewünschtes Pensum<input type="number" min="10" max="100" value={form.desired_employment_percent} onChange={e=>set("desired_employment_percent",e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="text-sm font-bold">Max. Entfernung (km)<input type="number" min="1" value={form.preferred_radius_km} onChange={e=>set("preferred_radius_km",e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["remote_ok","Homeoffice möglich"],["shift_work_ok","Schichtarbeit möglich"],["driving_license_b","Führerschein B"]].map(([k,l])=><label key={k} className="flex items-center gap-3 rounded-xl border p-4 text-sm font-semibold"><input type="checkbox" checked={Boolean(form[k as keyof Form])} onChange={e=>set(k as keyof Form,e.target.checked)} className="h-4 w-4"/>{l}</label>)}</div></section>
    <section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Sichtbarkeit</h2><div className="mt-5 space-y-3"><label className="flex items-start gap-3 rounded-xl bg-slate-50 p-4"><input type="checkbox" checked={form.profile_visible} onChange={e=>set("profile_visible",e.target.checked)} className="mt-1 h-4 w-4"/><span><b>Mein Profil für passende Arbeitgeber sichtbar machen</b><small className="mt-1 block text-slate-500">Dein Profil kann in passenden Suchergebnissen erscheinen.</small></span></label><label className="flex items-start gap-3 rounded-xl bg-slate-50 p-4"><input type="checkbox" checked={form.contact_visible} onChange={e=>set("contact_visible",e.target.checked)} className="mt-1 h-4 w-4"/><span><b>Kontaktaufnahme erlauben</b><small className="mt-1 block text-slate-500">Arbeitgeber können dir über Stoyan eine Kontaktanfrage senden.</small></span></label></div></section>
    {notice&&<div className="rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-800">{notice}</div>}<div className="flex flex-wrap justify-end gap-3"><Link href="/arbeitnehmer" className="rounded-lg border px-6 py-3 font-bold">Abbrechen</Link><button disabled={saving} className="rounded-lg bg-blue-600 px-6 py-3 font-bold text-white disabled:opacity-50">{saving?"Speichern…":"Profil speichern"}</button></div>
  </form></div></main>
}
