"use client"
import Link from "next/link"
import { useEffect,useState } from "react"
import { createClient } from "@/lib/supabase/client"

type ImageRow={id:string;image_url:string;image_name:string|null;image_position:number}

export default function BilderPage(){
 const [files,setFiles]=useState<File[]>([]);const [images,setImages]=useState<ImageRow[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false)
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return}const {data,error}=await s.from("employee_images").select("id,image_url,image_name,image_position").eq("employee_id",user.id).order("image_position");if(error){setMessage(error.message);return}setImages((data||[]) as ImageRow[])})()},[])
 async function upload(){setMessage("");if(!files.length)return;setBusy(true);const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){window.location.href="/login";return}for(let i=0;i<files.length;i++){const file=files[i];if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024){setMessage("Bitte JPG, PNG oder WEBP bis 10 MB verwenden.");continue}const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${user.id}/gallery-${Date.now()}-${i}.${ext}`;const up=await s.storage.from("employee-media").upload(path,file,{contentType:file.type});if(up.error){setMessage(up.error.message);continue}const {data:url}=s.storage.from("employee-media").getPublicUrl(path);const row=await s.from("employee_images").insert({employee_id:user.id,image_url:url.publicUrl,image_name:file.name,image_position:images.length+i});if(row.error){setMessage(row.error.message);continue}}const {data}=await s.from("employee_images").select("id,image_url,image_name,image_position").eq("employee_id",user.id).order("image_position");setImages((data||[]) as ImageRow[]);setFiles([]);setMessage("Bilder erfolgreich hochgeladen.");setBusy(false)}
 async function remove(id:string){const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const row=images.find(x=>x.id===id);const result=await s.from("employee_images").delete().eq("id",id);if(result.error){setMessage(result.error.message);return}if(row){const path=row.image_url.split("/employee-media/")[1];if(path)await s.storage.from("employee-media").remove([decodeURIComponent(path)])}setImages(x=>x.filter(i=>i.id!==id))}
 return <div className="animate-fade-up"><div className="mx-auto max-w-5xl"><p className="text-sm font-black uppercase tracking-widest text-[var(--brand)]">Meine Bilder</p><h1 className="mt-2 text-4xl font-black text-[var(--navy)]">Dein Profil. Deine Geschichte.</h1><p className="mt-3 max-w-2xl text-[var(--muted)]">Zeige Arbeitgebern mit professionellen Bildern einen authentischen Eindruck von dir und deiner Arbeit.</p><section className="card card-pad mt-8"><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>setFiles(Array.from(e.target.files||[]))} className="block w-full rounded-xl border border-[var(--line)] p-4"/><p className="mt-2 text-sm text-[var(--muted)]">JPG, PNG oder WEBP · maximal 10 MB pro Bild</p>{files.length>0&&<p className="mt-2 text-sm font-semibold text-[var(--navy)]">{files.length} Bild{files.length===1?"":"er"} ausgewählt</p>}<button onClick={upload} disabled={busy||!files.length} className="btn-primary mt-5 disabled:opacity-50">{busy?"Hochladen…":"Bilder hochladen"}</button>{message&&<p className="mt-4 rounded-xl border border-[var(--brand)]/20 bg-[var(--brand)]/8 p-3 text-sm font-semibold text-[var(--brand)]">{message}</p>}</section><section className="mt-8"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{images.map(i=><div key={i.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><img src={i.image_url} alt={i.image_name||"Profilbild"} className="aspect-square w-full object-cover"/><div className="flex items-center justify-between gap-3 p-4"><span className="truncate text-sm font-semibold">{i.image_name||"Bild"}</span><button onClick={()=>remove(i.id)} className="shrink-0 text-sm font-bold text-red-600">Löschen</button></div></div>)}</div>{!images.length&&<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-slate-500">Noch keine Bilder hochgeladen.</div>}</section></div></div>}
