"use client"

import Link from "next/link"
import { useEffect, useState } from "react"
import { ArrowLeft, Building2, LogOut, Mail, Pencil, ShieldCheck, UserRound } from "lucide-react"
import { createClient } from "@/lib/supabase/client"

type Profile={first_name?:string|null;last_name?:string|null;phone?:string|null;city?:string|null;postal_code?:string|null}
type Company={name?:string|null;industry?:string|null;city?:string|null}

export default function KontoPage(){
 const s=createClient(); const [loading,setLoading]=useState(true); const [loggingOut,setLoggingOut]=useState(false); const [email,setEmail]=useState(""); const [role,setRole]=useState<"employee"|"employer"|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [company,setCompany]=useState<Company|null>(null)
 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return};const r=user.user_metadata?.role==="employer"?"employer":"employee";setEmail(user.email||"");setRole(r);if(r==="employer"){const {data}=await s.from("companies").select("name,industry,city").eq("owner_id",user.id).maybeSingle();if(active)setCompany(data)}else{const {data}=await s.from("profiles").select("first_name,last_name,phone,city,postal_code").eq("id",user.id).maybeSingle();if(active)setProfile(data)}if(active)setLoading(false)})();return()=>{active=false}},[])
 async function logout(){setLoggingOut(true);await s.auth.signOut();location.href="/"}
 if(loading)return <main className="min-h-screen bg-slate-50 px-6 py-16"><div className="mx-auto max-w-4xl rounded-3xl bg-white p-10 text-center shadow-sm">Konto wird geladen…</div></main>
 const name=role==="employer"?(company?.name||"Mein Unternehmen"):[profile?.first_name,profile?.last_name].filter(Boolean).join(" ")||"Mein Profil";const edit=role==="employer"?"/arbeitgeber/firma":"/arbeitnehmer/profil";const dashboard=role==="employer"?"/arbeitgeber":"/arbeitnehmer";const requests=role==="employer"?"/arbeitgeber/anfragen":"/arbeitnehmer/anfragen"
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6 sm:py-12"><div className="mx-auto max-w-5xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-950"><ArrowLeft className="h-4 w-4"/> Zur Startseite</Link><section className="mt-6 rounded-[30px] bg-slate-950 p-7 text-white shadow-xl sm:p-10"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/10">{role==="employer"?<Building2 className="h-8 w-8"/>:<UserRound className="h-8 w-8"/>}</div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-300">Mein Konto</p><h1 className="mt-1 text-3xl font-black">{name}</h1><p className="mt-1 text-sm text-slate-300">{role==="employer"?"Arbeitgeber":"Arbeitnehmer"}</p></div></div><button onClick={logout} disabled={loggingOut} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/10 px-5 py-3 font-bold hover:bg-red-500/20 disabled:opacity-50"><LogOut className="h-4 w-4"/>{loggingOut?"Abmelden…":"Abmelden"}</button></div></section>
 <div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black text-slate-950">Konto & Profil</h2><Link href={edit} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-600"><Pencil className="h-4 w-4"/> Bearbeiten</Link></div><div className="mt-6 space-y-4 text-sm"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">E-Mail</p><p className="mt-1 break-all font-semibold">{email||"Keine E-Mail"}</p></div>{role==="employee"&&<><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Name</p><p className="mt-1 font-semibold">{[profile?.first_name,profile?.last_name].filter(Boolean).join(" ")||"Nicht angegeben"}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Ort</p><p className="mt-1 font-semibold">{[profile?.postal_code,profile?.city].filter(Boolean).join(" ")||"Nicht angegeben"}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Telefon</p><p className="mt-1 font-semibold">{profile?.phone||"Nicht angegeben"}</p></div></>}{role==="employer"&&<><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Unternehmen</p><p className="mt-1 font-semibold">{company?.name||"Nicht angegeben"}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Branche</p><p className="mt-1 font-semibold">{company?.industry||"Nicht angegeben"}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Ort</p><p className="mt-1 font-semibold">{company?.city||"Nicht angegeben"}</p></div></>}</div></section>
 <section className="rounded-3xl border border-blue-100 bg-blue-50 p-6 shadow-sm"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-blue-600"/><h2 className="font-black text-slate-950">Datenschutz</h2></div><p className="mt-3 text-sm leading-6 text-slate-600">Verwalte deine Sichtbarkeit, lade deine Daten herunter, berichtige Angaben oder lösche dein Konto.</p><div className="mt-5 space-y-3"><Link href="/datenschutz-einstellungen" className="flex items-center justify-center rounded-xl bg-slate-950 px-5 py-3 font-bold text-white hover:bg-blue-600">Datenschutz-Einstellungen</Link><Link href="/datenschutz" className="flex items-center justify-center rounded-xl border border-slate-200 bg-white px-5 py-3 font-bold text-slate-800 hover:bg-slate-50">Datenschutzerklärung</Link></div></section></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><Link href={edit} className="rounded-2xl border border-slate-200 bg-white p-5 font-bold shadow-sm hover:bg-slate-50"><Pencil className="mr-2 inline h-4 w-4"/> Profildaten bearbeiten</Link><Link href={requests} className="rounded-2xl border border-slate-200 bg-white p-5 font-bold shadow-sm hover:bg-slate-50"><Mail className="mr-2 inline h-4 w-4"/> Kontaktanfragen & Chats</Link></div><Link href={dashboard} className="mt-3 block rounded-2xl border border-slate-200 bg-white p-5 text-center font-bold shadow-sm hover:bg-slate-50">Zum Dashboard</Link></div></main>
}
