import Link from "next/link"

const categories = [
  ["IT & Technologie", "Software, Support, Data & mehr", "/images/technology.svg"],
  ["Handwerk", "Technik, Bau, Werkstatt", "/images/craft.svg"],
  ["Logistik", "Lager, Transport & Disposition", "/images/logistics.svg"],
  ["Automobil", "Werkstatt, Diagnose & Service", "/images/automotive.svg"],
]

function Check({children}:{children:React.ReactNode}) { return <span className="flex items-center gap-2 text-sm font-semibold text-slate-600"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 text-xs font-black text-blue-700">✓</span>{children}</span> }

export default function Home() {
  return <main className="min-h-screen bg-white text-[#16212b]">
    <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur"><nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8"><Link href="/" className="text-3xl font-black tracking-tight">Stoyan<span className="text-blue-600">.</span></Link><div className="hidden items-center gap-8 text-sm font-semibold text-slate-600 lg:flex"><a href="#jobs" className="hover:text-blue-600">Jobs</a><a href="#arbeitnehmer" className="hover:text-blue-600">Für Arbeitnehmer</a><a href="#arbeitgeber" className="hover:text-blue-600">Für Arbeitgeber</a><a href="#matching" className="hover:text-blue-600">Matching</a></div><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-lg px-4 py-2.5 font-bold text-slate-700 hover:bg-slate-50 sm:block">Anmelden</Link><Link href="/registrieren?role=employer" className="rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-blue-700">Stelle aufgeben</Link></div></nav></header>

    <section className="overflow-hidden bg-[#f4f7fb]"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-12 sm:px-8 sm:py-20 lg:grid-cols-[.9fr_1.1fr] lg:py-24"><div><p className="mb-5 text-sm font-black uppercase tracking-[.18em] text-blue-600">Die Job-Matching-Plattform</p><h1 className="max-w-2xl text-5xl font-black leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-[72px]">Dein nächster Job.<br/><span className="text-blue-600">Dein nächster Mitarbeiter.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">Stoyan verbindet Menschen und Unternehmen anhand von Qualifikationen, Erfahrung, Skills, Arbeitsort und persönlichen Vorstellungen.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/registrieren?role=employee" className="rounded-lg bg-blue-600 px-6 py-3.5 font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700">Jobs entdecken</Link><Link href="/registrieren?role=employer" className="rounded-lg border border-slate-300 bg-white px-6 py-3.5 font-bold hover:bg-slate-50">Mitarbeiter finden</Link></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3"><Check>Kostenloses Profil</Check><Check>Transparente Matches</Check><Check>Für Arbeitnehmer & Arbeitgeber</Check></div></div><div className="relative"><div className="overflow-hidden rounded-[32px] shadow-2xl ring-1 ring-slate-200"><img src="/images/hero.svg" alt="Stoyan Matching Plattform" className="aspect-[4/3] w-full object-cover"/></div><div className="absolute -bottom-6 left-5 w-[calc(100%-40px)] max-w-sm rounded-2xl border border-slate-200 bg-white p-4 shadow-2xl sm:left-8"><div className="flex items-center gap-3"><img src="/images/employee.svg" alt="Kandidat" className="h-12 w-12 rounded-xl object-cover"/><div><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">Passender Kandidat</p><p className="font-black">Automobil-Mechatroniker</p><p className="text-xs text-slate-500">Luzern · 5 Jahre Erfahrung</p></div><div className="ml-auto text-right"><p className="text-2xl font-black text-blue-600">94%</p><p className="text-[11px] font-bold text-slate-400">MATCH</p></div></div></div></div></div></section>

    <section id="jobs" className="relative z-10 mx-auto -mt-1 max-w-6xl px-5 sm:px-8"><div className="rounded-2xl border border-slate-200 bg-white p-3 shadow-xl sm:p-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><div className="rounded-xl border border-slate-200 px-5 py-3.5"><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">Was suchst du?</p><p className="mt-1 font-semibold">Beruf, Position oder Stichwort</p></div><div className="rounded-xl border border-slate-200 px-5 py-3.5"><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">Wo?</p><p className="mt-1 font-semibold">Ort oder PLZ</p></div><Link href="/registrieren?role=employee" className="flex items-center justify-center rounded-xl bg-slate-950 px-8 font-bold text-white hover:bg-slate-800">Jobs suchen</Link></div></div></section>

    <section id="matching" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="text-sm font-black uppercase tracking-[.18em] text-blue-600">Matching</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-5xl">Nicht irgendein Job.<br/>Der richtige.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Arbeitgeber definieren ihre Anforderungen. Arbeitnehmer zeigen, was sie können und suchen. Stoyan macht daraus nachvollziehbare Matches.</p></div><div className="rounded-[28px] bg-slate-950 p-7 text-white shadow-xl sm:p-9"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-slate-400">STELLE</p><h3 className="mt-2 text-2xl font-black">Automobil-Mechatroniker EFZ</h3><p className="mt-2 text-slate-400">Luzern · 100 % · Festanstellung</p></div><strong className="rounded-full bg-blue-600 px-4 py-2 text-sm">94 % Match</strong></div><div className="mt-8 grid gap-5 sm:grid-cols-2">{[["Ausbildung","100%","w-full"],["Erfahrung","95%","w-[95%]"],["Skills","92%","w-[92%]"],["Arbeitsort","96%","w-[96%]"]].map(([n,v,w])=><div key={n}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-400">{n}</span><b>{v}</b></div><div className="h-2 rounded-full bg-white/10"><div className={`h-2 rounded-full bg-blue-500 ${w}`}/></div></div>)}</div></div></div></section>

    <section id="arbeitnehmer" className="border-y border-slate-200 bg-[#f4f7fb]"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-24 sm:px-8 lg:grid-cols-2"><div className="overflow-hidden rounded-[32px] shadow-xl"><img src="/images/employee.svg" alt="Arbeitnehmerprofil" className="aspect-[4/3] w-full object-cover"/></div><div><p className="text-sm font-black uppercase tracking-[.18em] text-blue-600">Für Arbeitnehmer</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-5xl">Dein Profil kann mehr als ein Lebenslauf.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Ausbildung, Berufserfahrung, Skills, Wunschposition, Arbeitsort, Pensum, Lohnvorstellung und Verfügbarkeit – alles an einem Ort.</p><div className="mt-7 space-y-3"><Check>Ein Profil für mehrere Bewerbungen</Check><Check>Passende Stellen auf einen Blick</Check><Check>Arbeitgeber sehen relevante Qualifikationen</Check></div><Link href="/registrieren?role=employee" className="mt-8 inline-flex rounded-lg bg-slate-950 px-6 py-3.5 font-bold text-white hover:bg-slate-800">Profil erstellen</Link></div></div></section>

    <section id="arbeitgeber" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-blue-600">Für Arbeitgeber</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-5xl">Die richtigen Mitarbeiter finden – ohne stundenlang zu suchen.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Erstellen Sie eine präzise Stelle und legen Sie fest, welche Qualifikationen, Erfahrung und Rahmenbedingungen wichtig sind.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border p-5"><p className="font-black">01</p><p className="mt-3 font-bold">Stelle erstellen</p><p className="mt-1 text-sm text-slate-500">Anforderungen definieren.</p></div><div className="rounded-2xl border p-5"><p className="font-black">02</p><p className="mt-3 font-bold">Matches erhalten</p><p className="mt-1 text-sm text-slate-500">Kandidaten vergleichen.</p></div><div className="rounded-2xl border p-5"><p className="font-black">03</p><p className="mt-3 font-bold">Kontakt aufnehmen</p><p className="mt-1 text-sm text-slate-500">Profile prüfen und auswählen.</p></div></div><Link href="/registrieren?role=employer" className="mt-8 inline-flex rounded-lg bg-blue-600 px-6 py-3.5 font-bold text-white hover:bg-blue-700">Stellenanzeige schalten</Link></div><div className="overflow-hidden rounded-[32px] shadow-xl"><img src="/images/employer.svg" alt="Arbeitgeber und Recruiting" className="aspect-[4/3] w-full object-cover"/></div></div></section>

    <section className="border-y border-slate-200 bg-[#f4f7fb]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><p className="text-sm font-black uppercase tracking-[.18em] text-blue-600">Branchen</p><div className="mt-3 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><h2 className="text-4xl font-black tracking-[-.04em]">Finde deine Richtung.</h2><Link href="/registrieren?role=employee" className="font-bold text-blue-600">Alle Jobs ansehen →</Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{categories.map(([title,desc,image])=><div key={title} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="overflow-hidden"><img src={image} alt={title} className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-5"><h3 className="font-black">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{desc}</p></div></div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="overflow-hidden rounded-[32px] bg-slate-950 px-7 py-14 text-white sm:px-12 sm:py-16"><div className="grid items-center gap-10 lg:grid-cols-[1fr_360px]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-blue-400">Stoyan</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] sm:text-5xl">Bereit für den nächsten Schritt?</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-400">Erstelle dein Profil oder veröffentliche deine erste Stelle.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/registrieren?role=employee" className="rounded-lg bg-blue-600 px-6 py-3.5 font-bold text-white hover:bg-blue-500">Als Arbeitnehmer starten</Link><Link href="/registrieren?role=employer" className="rounded-lg bg-white px-6 py-3.5 font-bold text-slate-950 hover:bg-slate-100">Als Arbeitgeber starten</Link></div></div><img src="/images/office.svg" alt="Modernes Arbeitsumfeld" className="hidden rounded-2xl lg:block"/></div></div></section>

    <footer className="border-t border-slate-200"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 sm:px-8 sm:flex-row sm:items-center sm:justify-between"><span className="text-xl font-black text-slate-950">Stoyan<span className="text-blue-600">.</span></span><span>Die Matching-Plattform für Arbeitnehmer und Arbeitgeber.</span></div></footer>
  </main>
}
