import Link from "next/link"

export const metadata = { title: "Datenschutzerklärung – JobMatch24", description: "Datenschutzerklärung von JobMatch24" }

export default function DatenschutzPage() {
  return <main className="min-h-screen bg-slate-50 px-4 py-10 sm:px-6 sm:py-16"><article className="mx-auto max-w-4xl rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10"><Link href="/" className="text-sm font-bold text-blue-600 hover:text-blue-700">← Zur Startseite</Link><p className="mt-8 text-sm font-black uppercase tracking-widest text-blue-600">JobMatch24</p><h1 className="mt-2 text-4xl font-black text-slate-950">Datenschutzerklärung</h1><p className="mt-4 text-sm text-slate-500">Stand: 3. September 2026</p>

<section className="prose prose-slate mt-10 max-w-none"><h2>1. Verantwortlicher</h2><p>Verantwortlich für die Bearbeitung von Personendaten im Zusammenhang mit JobMatch24 ist der Betreiber von JobMatch24. Datenschutzanfragen können direkt über die <Link href="/datenschutz-einstellungen">Datenschutz-Einstellungen</Link> eingereicht werden.</p>
<h2>2. Welche Daten wir bearbeiten</h2><p>Je nach Nutzung können insbesondere Konto- und Kontaktdaten (Name, E-Mail-Adresse, Telefonnummer, Ort und PLZ), berufliche Angaben (Beruf, Ausbildung, Erfahrung, Skills, Sprachen), Angaben zu Arbeitswünschen und Verfügbarkeit, Profilbilder, Unternehmensdaten, Kontaktanfragen, Nachrichten, Bewerbungen, Matching-Daten sowie Abonnement- und technische Kontodaten bearbeitet werden.</p>
<h2>3. Zwecke</h2><p>Wir bearbeiten Personendaten insbesondere, um Konten bereitzustellen und zu sichern, Arbeitnehmer und Arbeitgeber zu verbinden, Profile und Suchfunktionen bereitzustellen, Kontaktanfragen und Nachrichten zu ermöglichen, Matching-Funktionen auszuführen, Abonnements abzuwickeln, Missbrauch und Sicherheitsvorfälle zu verhindern und gesetzliche bzw. vertragliche Pflichten zu erfüllen.</p>
<h2>4. Sichtbarkeit und Kontrolle</h2><p>Arbeitnehmer können die Sichtbarkeit ihres Profils und die Erlaubnis für Kontaktanfragen in den Datenschutz-Einstellungen steuern. Kontaktinformationen werden nicht als Teil der normalen Kandidatensuche angezeigt. Die technische Zugriffssteuerung erfolgt über Authentifizierung und Datenbank-Zugriffsregeln.</p>
<h2>5. Matching und Profiling</h2><p>JobMatch24 kann Angaben wie Beruf, Erfahrung, Skills, Ausbildung, Pensum, Lohnvorstellung und Ort verwenden, um passende Profile bzw. Stellen zu ermitteln. Ein Matching-Score ist eine technische Unterstützung für die Suche und keine automatische Entscheidung über die Einstellung einer Person. Bei einer automatisierten Einzelentscheidung im Sinne des DSG informieren wir die betroffene Person gesondert über die dafür erforderlichen Angaben.</p>
<h2>6. Empfänger und Dienstleister</h2><p>Für den Betrieb können technische Dienstleister eingesetzt werden, insbesondere Anbieter für Hosting, Datenbank/Auth, Zahlungsabwicklung und E-Mail-Versand. Personendaten werden nur im für den jeweiligen Zweck erforderlichen Umfang an solche Dienstleister übermittelt. Internationale Datenübermittlungen werden anhand der jeweils geltenden gesetzlichen Voraussetzungen und Garantien geprüft.</p>
<h2>7. Aufbewahrung</h2><p>Personendaten werden so lange aufbewahrt, wie sie für den jeweiligen Zweck erforderlich sind oder gesetzliche Aufbewahrungspflichten bestehen. Nicht mehr benötigte Daten werden gelöscht oder anonymisiert, soweit keine gesetzliche oder berechtigte Aufbewahrung entgegensteht.</p>
<h2>8. Datensicherheit</h2><p>Wir verwenden angemessene technische und organisatorische Massnahmen, insbesondere Authentifizierung, rollen- und zweckbezogene Zugriffsregeln sowie serverseitige Verarbeitung für privilegierte Vorgänge. Kein Internetdienst kann absolute Sicherheit garantieren.</p>
<h2>9. Deine Rechte</h2><p>Betroffene Personen können nach Massgabe des Schweizer Datenschutzgesetzes insbesondere Auskunft, Berichtigung und Löschung verlangen und einer Bearbeitung widersprechen. Die <Link href="/datenschutz-einstellungen">Datenschutz-Einstellungen</Link> ermöglichen einen direkten Datenexport sowie die Einreichung von Anfragen.</p>
<h2>10. Auskunft und Datenexport</h2><p>Angemeldete Personen können über ihr Konto einen Export der im JobMatch24-System verfügbaren kontobezogenen Daten anfordern bzw. herunterladen. Aus Sicherheitsgründen werden solche Daten nur nach erfolgreicher Authentifizierung bereitgestellt.</p>
<h2>11. Löschung des Kontos</h2><p>Ein Konto kann über die Datenschutz-Einstellungen endgültig gelöscht werden. Dabei werden die mit dem Konto verbundenen Daten und – soweit technisch möglich und rechtlich zulässig – die zugehörigen Dateien gelöscht. Gesetzliche Aufbewahrungspflichten oder andere gesetzlich zulässige Gründe können einzelne Daten von einer sofortigen Löschung ausnehmen.</p>
<h2>12. Cookies und ähnliche Technologien</h2><p>Für die Anmeldung und den sicheren Betrieb können technisch notwendige Cookies bzw. Session-Technologien verwendet werden. Nicht notwendiges Tracking sollte nur eingesetzt werden, wenn die dafür erforderlichen datenschutzrechtlichen Voraussetzungen erfüllt sind.</p>
<h2>13. Änderungen</h2><p>Diese Datenschutzerklärung kann angepasst werden, wenn sich Funktionen, Dienstleister oder rechtliche Anforderungen ändern. Die jeweils aktuelle Fassung wird auf dieser Seite veröffentlicht.</p></section>

<div className="mt-10 rounded-2xl bg-slate-50 p-5 text-sm text-slate-600"><b>Wichtig:</b> Diese Erklärung ist auf den aktuell bekannten Funktionsumfang von JobMatch24 ausgerichtet. Vor dem produktiven Einsatz sollten Betreiberangaben, konkrete Dienstleister/Verträge, Speicherfristen und internationale Übermittlungen rechtlich abschliessend geprüft und ergänzt werden.</div></article></main>
}
