import Link from "next/link"
import { createClient } from "@/lib/supabase/server"

export default async function DashboardPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const role = user?.user_metadata?.role
  if (!user) return <main className="p-10"><h1 className="text-2xl font-bold">Nicht angemeldet</h1><Link href="/login" className="text-blue-600">Zum Login</Link></main>
  const isEmployer = role === "employer"
  return <main className="min-h-screen bg-slate-50 px-6 py-12"><div className="mx-auto max-w-6xl"><div className="rounded-3xl bg-white p-8 shadow-sm"><div className="flex items-start justify-between gap-6"><div><p className="text-sm font-semibold text-blue-600">STOYAN</p><h1 className="mt-2 text-4xl font-black">Willkommen zurück</h1><p className="mt-3 text-slate-600">{user.email}</p></div><Link href="/" className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">Startseite</Link></div><div className="mt-8 rounded-2xl bg-slate-50 p-6"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Konto</p><h2 className="mt-2 text-xl font-black">{isEmployer ? "Arbeitgeber" : role === "employee" ? "Arbeitnehmer" : "Rolle noch nicht festgelegt"}</h2></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Link href={isEmployer?"/arbeitgeber":"/arbeitnehmer"} className="rounded-2xl bg-blue-600 p-6 text-white shadow-sm hover:bg-blue-700"><p className="text-sm font-bold opacity-80">{isEmployer?"ARBEITGEBER":"ARBEITNEHMER"}</p><h2 className="mt-2 text-2xl font-black">{isEmployer?"Kandidaten suchen":"Mein Profil öffnen"}</h2><p className="mt-2 text-sm opacity-80">{isEmployer?"Kriterien festlegen und passende Arbeitnehmer finden.":"Profil, Erfahrung, Skills und Arbeitswünsche verwalten."}</p></Link><Link href={isEmployer?"/arbeitgeber#firma":"/arbeitnehmer/profil"} className="rounded-2xl border border-slate-200 p-6 hover:border-blue-200 hover:bg-blue-50"><p className="text-sm font-bold text-slate-400">VERWALTUNG</p><h2 className="mt-2 text-2xl font-black">{isEmployer?"Unternehmen":"Profil bearbeiten"}</h2><p className="mt-2 text-sm text-slate-500">{isEmployer?"Firmeninformationen und Recruiting vorbereiten.":"Persönliche und berufliche Angaben vervollständigen."}</p></Link></div></div></div></main>
}
